Update fonction_aléatoire.py
Choice caused problem because removes removed all the variable from the list

Traceback (most recent call last):
  File "c:\Users\wenwe\OneDrive\Desktop\Projet_Final\Core\Aléatoire\fonction_aléatoire.py", line 62, in <module>
    print(aléatoire())
          ~~~~~~~~~^^
  File "c:\Users\wenwe\OneDrive\Desktop\Projet_Final\Core\Aléatoire\fonction_aléatoire.py", line 24, in aléatoire
    Random_game=random.choice(liste_jeux)
  File "C:\Users\wenwe\AppData\Local\Programs\Python\Python313\Lib\random.py", line 351, in choice
    raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence